// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACBEUX1VUT-QitogKBlfZgSQaA0_CIytM',
    appId: '1:928021779325:web:4984a7a9aacdbeb3cd7214',
    messagingSenderId: '928021779325',
    projectId: 'chatter-f087b',
    authDomain: 'chatter-f087b.firebaseapp.com',
    storageBucket: 'chatter-f087b.appspot.com',
    measurementId: 'G-3QESRENLWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHl5RxIvBO_Ejxu6n3tbaBiJZR2IJ3Cfk',
    appId: '1:928021779325:android:a5ce4f74f700e630cd7214',
    messagingSenderId: '928021779325',
    projectId: 'chatter-f087b',
    storageBucket: 'chatter-f087b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpJnDSifXIyxdSZRZSlNkCKjo0dvnx0iE',
    appId: '1:928021779325:ios:69be5f98ee3be185cd7214',
    messagingSenderId: '928021779325',
    projectId: 'chatter-f087b',
    storageBucket: 'chatter-f087b.appspot.com',
    iosClientId: '928021779325-mh9025m77imc6kpio25p4hner6838ch2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpJnDSifXIyxdSZRZSlNkCKjo0dvnx0iE',
    appId: '1:928021779325:ios:69be5f98ee3be185cd7214',
    messagingSenderId: '928021779325',
    projectId: 'chatter-f087b',
    storageBucket: 'chatter-f087b.appspot.com',
    iosClientId: '928021779325-mh9025m77imc6kpio25p4hner6838ch2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatter',
  );
}
